version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -sharedDb"

  invoice:
    build: .
    image: invoice
    hostname: invoice
    container_name: invoice
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=ABC1234567890XYZQWER
      - AWS_SECRET_ACCESS_KEY=QWERTYUIOPASDFGHJKLZXCVBNM1234567890XYZ1